/**
 * Build script for moltendb-wasm npm package.
 *
 * Steps:
 *   1. Copy wasm-pack output (pkg/) into dist/
 *   2. Copy the Web Worker (with import path fixed to ./moltendb.js)
 *   3. Copy the main-thread MoltenDB client (with worker path parameterised)
 *   4. Generate TypeScript declarations for the client
 */

import { copyFileSync, mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root    = resolve(__dirname, '../..');   // MoltenDB project root
const pkgDir  = resolve(root, 'pkg');
const distDir = resolve(__dirname, '../dist');

// ── 1. Clean and recreate dist/ ───────────────────────────────────────────────
if (existsSync(distDir)) rmSync(distDir, { recursive: true });
mkdirSync(distDir, { recursive: true });

// ── 2. Copy wasm-pack artifacts ───────────────────────────────────────────────
const wasmFiles = [
  'moltendb.js',
  'moltendb.d.ts',
  'moltendb_bg.wasm',
  'moltendb_bg.wasm.d.ts',
];
for (const f of wasmFiles) {
  copyFileSync(resolve(pkgDir, f), resolve(distDir, f));
  console.log(`  copied  pkg/${f}  →  dist/${f}`);
}

// ── 3. Write the Web Worker ───────────────────────────────────────────────────
// The worker imports moltendb.js from the same directory (dist/).
// When bundled by the consumer's build tool, the import will be resolved
// relative to wherever the worker file ends up.
const workerSrc = `// MoltenDB Web Worker — auto-generated by moltendb-wasm build script
// Do not edit directly; edit moltendb-wasm/scripts/build.mjs instead.
import init, { WorkerDb } from './moltendb.js';

let db = null;

self.onmessage = async (event) => {
    const { id, action, ...params } = event.data;

    try {
        if (!db && action === 'init') {
            await init();
            db = await new WorkerDb(params.dbName || 'moltendb');
            self.postMessage({ id, result: { status: 'initialized' } });
            return;
        }

        if (!db) {
            throw new Error('Database not initialized. Send an "init" message first.');
        }

        // Pass action + params but NOT id so the Rust validator does not see
        // 'id' as an unknown property.
        const result = db.handle_message({ action, ...params });
        self.postMessage({ id, result });

    } catch (error) {
        self.postMessage({ id, error: error.toString() });
    }
};
`;
writeFileSync(resolve(distDir, 'moltendb-worker.js'), workerSrc);
console.log('  wrote   dist/moltendb-worker.js');

// ── 4. Write the main-thread client (index.js) ────────────────────────────────
// The worker URL is passed in by the consumer so they can control how the
// worker file is served (bundler asset, CDN URL, new URL(...) pattern, etc.).
const clientSrc = `/**
 * MoltenDB main-thread client.
 *
 * Usage:
 *   import { MoltenDB } from 'moltendb-wasm';
 *
 *   const db = new MoltenDB('my-db', {
 *     // Required: URL or path to the moltendb-worker.js file.
 *     // With a bundler:  new URL('moltendb-wasm/worker', import.meta.url)
 *     // Plain script:    '/node_modules/moltendb-wasm/dist/moltendb-worker.js'
 *     workerUrl: new URL('moltendb-wasm/worker', import.meta.url),
 *   });
 *   await db.init();
 */
export class MoltenDB {
    /**
     * @param {string} dbName - OPFS file name (unique per database).
     * @param {object} [options]
     * @param {string|URL} [options.workerUrl] - URL to moltendb-worker.js.
     *   Defaults to './moltendb-worker.js' (works when served from the same directory).
     * @param {boolean} [options.syncEnabled=false] - Enable WebSocket sync.
     * @param {string}  [options.serverUrl='wss://localhost:1538/ws'] - WS server URL.
     * @param {number}  [options.syncIntervalMs=5000] - Sync batch flush interval.
     * @param {string}  [options.authToken] - JWT token for WS authentication.
     */
    constructor(dbName = 'moltendb', options = {}) {
        this.dbName         = dbName;
        this.workerUrl      = options.workerUrl ?? './moltendb-worker.js';
        this.worker         = null;
        this.messageId      = 0;
        this.pendingRequests = new Map();

        this.syncEnabled    = options.syncEnabled    ?? false;
        this.serverUrl      = options.serverUrl      ?? 'wss://localhost:1538/ws';
        this.syncIntervalMs = options.syncIntervalMs ?? 5000;
        this.authToken      = options.authToken      ?? null;

        this.ws             = null;
        this.syncCallbacks  = new Set();
        this.syncQueue      = [];
        this.syncTimer      = null;
    }

    /** Initialise the Web Worker and open the OPFS database. */
    async init() {
        return new Promise((resolve, reject) => {
            this.worker = new Worker(this.workerUrl, { type: 'module' });

            this.worker.onmessage = (event) => {
                const { id, result, error } = event.data;
                const pending = this.pendingRequests.get(id);
                if (!pending) return;
                this.pendingRequests.delete(id);
                if (error) pending.reject(new Error(error));
                else       pending.resolve(result);
            };

            this.worker.onerror = (err) => {
                console.error('[MoltenDB] Worker error:', err);
                reject(err);
            };

            this.sendMessage('init', { dbName: this.dbName })
                .then(() => this.syncEnabled ? this.connectSync() : undefined)
                .then(resolve)
                .catch(reject);
        });
    }

    /**
     * Send a raw message to the worker and return a Promise for the result.
     * @param {string} action
     * @param {object} [params]
     */
    sendMessage(action, params = {}) {
        return new Promise((resolve, reject) => {
            const id = this.messageId++;
            this.pendingRequests.set(id, { resolve, reject });
            this.worker.postMessage({ id, action, ...params });
        });
    }

    // ── WebSocket sync ────────────────────────────────────────────────────────

    connectSync() {
        return new Promise((resolve, reject) => {
            this.ws = new WebSocket(this.serverUrl);

            this.ws.onopen = () => {
                if (this.authToken) {
                    this.ws.send(JSON.stringify({ action: 'AUTH', token: this.authToken }));
                }
                if (this.syncTimer) clearInterval(this.syncTimer);
                this.syncTimer = setInterval(() => this.flushSyncQueue(), this.syncIntervalMs);
                resolve();
            };

            this.ws.onmessage = (event) => {
                try { this.handleServerUpdate(JSON.parse(event.data)); }
                catch (e) { console.error('[MoltenDB] Failed to parse server message:', e); }
            };

            this.ws.onclose = () => {
                if (this.syncTimer) clearInterval(this.syncTimer);
                setTimeout(() => this.connectSync(), 1538);
            };

            this.ws.onerror = (err) => reject(err);
        });
    }

    handleServerUpdate(update) {
        if (update.event === 'change' && update.collection && update.key) {
            // Re-fetch the updated document from the server and apply locally.
            // (The WS push only carries the key + new _v, not the full document.)
        }
        this.syncCallbacks.forEach(cb => cb(update));
    }

    /** Subscribe to real-time server push events. Returns an unsubscribe fn. */
    onSync(callback) {
        this.syncCallbacks.add(callback);
        return () => this.syncCallbacks.delete(callback);
    }

    flushSyncQueue() {
        if (!this.syncQueue.length || !this.ws || this.ws.readyState !== WebSocket.OPEN) return;
        const batch = this.syncQueue.splice(0);
        this.ws.send(JSON.stringify({ action: 'set', operations: batch }));
    }

    // ── Convenience CRUD helpers ──────────────────────────────────────────────

    /** Insert / upsert one document. */
    async set(collection, key, value, options = {}) {
        await this.sendMessage('set', { collection, data: { [key]: value } });
        if (this.syncEnabled && !options.skipSync) {
            this.syncQueue.push({ action: 'set', collection, data: { [key]: value } });
        }
    }

    /** Fetch a single document by key. */
    get(collection, key) {
        return this.sendMessage('get', { collection, keys: key });
    }

    /** Fetch all documents in a collection. */
    getAll(collection) {
        return this.sendMessage('get', { collection });
    }

    /** Delete a document by key. */
    async delete(collection, key, options = {}) {
        await this.sendMessage('delete', { collection, keys: key });
        if (this.syncEnabled && !options.skipSync) {
            this.syncQueue.push({ action: 'delete', collection, keys: key });
        }
    }

    /** Compact the OPFS log file. */
    compact() {
        return this.sendMessage('compact');
    }

    /** Close the WebSocket connection and stop the sync timer. */
    disconnect() {
        if (this.syncTimer) clearInterval(this.syncTimer);
        if (this.ws) this.ws.close();
    }

    /** Terminate the Web Worker (and disconnect sync). */
    terminate() {
        this.disconnect();
        if (this.worker) this.worker.terminate();
    }
}
`;
writeFileSync(resolve(distDir, 'index.js'), clientSrc);
console.log('  wrote   dist/index.js');

// ── 5. Write TypeScript declarations for the client ───────────────────────────
const dts = `export interface MoltenDBOptions {
  /** URL or path to moltendb-worker.js. Defaults to './moltendb-worker.js'. */
  workerUrl?: string | URL;
  /** Enable WebSocket sync with a MoltenDB server. Default: false. */
  syncEnabled?: boolean;
  /** WebSocket server URL. Default: 'wss://localhost:1538/ws'. */
  serverUrl?: string;
  /** Sync batch flush interval in ms. Default: 5000. */
  syncIntervalMs?: number;
  /** JWT token for WebSocket authentication. */
  authToken?: string;
}

export type SyncCallback = (update: {
  event: 'change' | 'delete' | 'drop';
  collection: string;
  key: string;
  new_v: number | null;
}) => void;

export class MoltenDB {
  readonly dbName: string;
  readonly worker: Worker | null;

  constructor(dbName?: string, options?: MoltenDBOptions);

  /** Initialise the Web Worker and open the OPFS database. */
  init(): Promise<void>;

  /** Send a raw message to the worker. */
  sendMessage(action: string, params?: Record<string, unknown>): Promise<unknown>;

  /** Insert / upsert one document. */
  set(collection: string, key: string, value: Record<string, unknown>, options?: { skipSync?: boolean }): Promise<void>;

  /** Fetch a single document by key. */
  get(collection: string, key: string): Promise<unknown>;

  /** Fetch all documents in a collection. */
  getAll(collection: string): Promise<unknown>;

  /** Delete a document by key. */
  delete(collection: string, key: string, options?: { skipSync?: boolean }): Promise<void>;

  /** Compact the OPFS log file. */
  compact(): Promise<unknown>;

  /** Subscribe to real-time server push events. Returns an unsubscribe function. */
  onSync(callback: SyncCallback): () => void;

  /** Close the WebSocket connection and stop the sync timer. */
  disconnect(): void;

  /** Terminate the Web Worker (and disconnect sync). */
  terminate(): void;
}
`;
writeFileSync(resolve(distDir, 'index.d.ts'), dts);
console.log('  wrote   dist/index.d.ts');

// ── 6. Copy LICENSE ───────────────────────────────────────────────────────────
const licSrc = resolve(root, 'LICENSE.md');
const licDst = resolve(__dirname, '../LICENSE.md');
if (existsSync(licSrc)) {
  copyFileSync(licSrc, licDst);
  console.log('  copied  LICENSE.md');
}

console.log('\n✅  moltendb-wasm dist/ built successfully.');
