const fs = require('fs');
const path = require('path');

const distPath = path.join(__dirname, '../dist');
const cjsFile = path.join(distPath, 'index.js');
const esmFile = path.join(distPath, 'index.esm.js');

if (!fs.existsSync(cjsFile)) {
    console.error('❌ dist/index.js not found. Make sure tsc runs first.');
    process.exit(1);
}

let code = fs.readFileSync(cjsFile, 'utf8');

// 1. Strip the CommonJS boilerplate generated by TypeScript
code = code.replace(/"use strict";\r?\n/g, '');
code = code.replace(/Object\.defineProperty\(exports,\s*"__esModule",\s*\{.*\}\);\r?\n/g, '');

// 2. Strip the `exports.X = exports.Y = void 0;` setup line
code = code.replace(/^exports\..*=\s*void 0;$/gm, '');

// 3. Convert CommonJS exports (exports.ClassName = ClassName;) to ESM (export { ClassName };)
code = code.replace(/^exports\.([a-zA-Z0-9_]+)\s*=\s*([a-zA-Z0-9_]+);$/gm, 'export { $2 as $1 };');

// Clean up any extra blank lines left behind by the regex stripping
code = code.replace(/\n\s*\n/g, '\n\n');

// Write the new ESM file
fs.writeFileSync(esmFile, code.trim() + '\n');

console.log('✅ Successfully generated dist/index.esm.js');