name: Version Packages (Develop)

on:
  push:
    branches:
      - develop
      -
permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Create Versioning PR
        uses: changesets/action@v1
        with:
          commit: "chore: version packages"
          title: "chore: version packages for next release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}